LocalProjects:
  Teste 1:
    Name: Teste 1
    DateTime: 2025-01-09T19:26:33.0000000
    Device: DESKTOP-7P120MF
    AsyncTime: 2025-02-04T18:22:46.7095798-03:00
    FolderId: 302035218842
    Status: 1
    Id: 51QrtadAg35gbQI10NUy
    metaDataProject:
      description: ''
      public_files: []
      url_image: ''
    url_readme: Teste_1
  teste 2:
    Name: teste 2
    DateTime: 2025-02-04T12:06:28.6113297-03:00
    Device: DESKTOP-7P120MF
    AsyncTime: 2025-02-04T18:23:15.2403932-03:00
    FolderId: 305950083622
    Status: 1
    Id: 7586cb8b-99c5-45b3-b174-2ec29a818377
    metaDataProject:
      description: ''
      public_files:
      - extention: txt
        name: A.txt
        share: https://app.box.com/s/yq6mdubt8zs66xoaflyo5ow2yjh7wdl9
      - extention: txt
        name: mic.txt
        share: https://app.box.com/s/wsx0hddwfs2k6ulips927xz20wc3llbw
      url_image: ''
    url_readme: teste 2.md
